language: perl
addons:
  apt:
    packages:
    - python-pip
install:
- pip install --user docutils
script:
- find -name "*.rst" | xargs -L1 -t -I{} ~/.local/bin/rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
