language: perl
before_install:
- sudo apt-get update
- sudo apt-get install --no-install-recommends python-pip
install:
- sudo pip install docutils
script:
- find -name "*.rst" | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null

# vim:ts=2 sts=2 sw=2 et
