dist: trusty
language: perl
perl:
- "5.10"
- "5.28"
addons:
  apt:
    packages:
    - libaspell-dev
install:
- export PERL_CPANM_OPT='--no-interactive --no-man-pages --notest --skip-satisfied'
- cpanm Text::Aspell
script:
- prove --verbose
jobs:
  include:
  - perl: null
    addons: []
    install:
    - python -m pip install --user restructuredtext-lint
    script:
    - dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
    - restructuredtext-lint --encoding=UTF-8 README.rst

# vim:ts=2 sts=2 sw=2 et
