dist: trusty
language: perl
install:
- python -m pip install --user docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- private/check-rst
- prove --verbose

# vim:ts=2 sts=2 sw=2 et
