#!/bin/sh
name=irssi-spellcheck
url=http://bitbucket.org/jwilk/irssi-spellcheck
if [ $# -ne 1 ]
then
    printf "%s <version>\n" "$0" >&2
    exit 1
fi
set -e -x
pwd="$PWD"
version="$1"
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS="--owner root --group root --mode a+rX --format ustar"
export GZIP="-9 -n"
mkdir -p "$sourceroot/$name-$version"
if [ -d .hg ]
then
    hg archive -r "$version" "$sourceroot/$name-$version"
else
    hg clone -r "$version" "$url" "$sourceroot/$name-$version"
fi
cd "$sourceroot"/*
rm -rf .hg*
mv "$(readlink -f doc/README)" doc/README
cd ..
tar -czf "$pwd/$name-$version.tar.gz" */
rm -rf "$sourceroot"

# vim:ts=4 sw=4 et
