#!/bin/sh
export version=${1:?"no version number provided"}
set -e
PS4='$ '
set -x
dch -m -v "$version" -u low -c doc/changelog
perl -pi -e 's/^(\$VERSION) = \047\K[\w.]+/$ENV{version}/' spellcheck.pl
