name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        os:
        - ubuntu-18.04
        - ubuntu-20.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: check Perl version
      run: |
        perl --version
    - name: apt install deps
      run:
        sudo apt-get install --no-install-recommends
          libtext-aspell-perl
    - name: run tests
      run: |
        prove --verbose
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: check changelog syntax
      run: |
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
    - name: check README syntax
      run: |
        python -m pip install restructuredtext-lint
        rst-lint --level=info --encoding=UTF-8 README
    - name: check SVG syntax
      run: |
        python -m pip install html5validator
        html5validator --svg doc/*.svg

# vim:ts=2 sts=2 sw=2 et
